### ISSUE TITLE
How can i add Chinese Font and input Chinese?

### ISSUE THREAD

**Issue by xiaolds** [ONLYOFFICE/dictionaries#2]
I installed Document Server in CentOS 7 with Docker successfully, but i find it can't convert successfully when the name of file contains Chinese. And the content of file can't be displayed correctly even i chose "utf-8" coding. I tried to install new Chinese Font on my server, but the problem still remained.

I tried my best and have to ask you for helping here~

**Comment by trofim24** [comment]
1. For convert problem: could you provide the log conversion. It lies in the file `/var/log/onlyoffice/documentserver/converter/out.log` ?
2. For display problem: сould you provide us with the file that is displayed is not correct, or a screenshot and the file name ?

And yes, this dictionary project. With your permission, I will close this Issue.
Could you open a new Issue in the repository [DocumentServer](https://github.com/ONLYOFFICE/DocumentServer) with all the additional data. 
Thank you.

**Comment by xiaolds** [comment]
Yes , I will open a new Issue in DocumentServer, and Thank you very much~
